import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter, Space_Grotesk } from 'next/font/google';
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: "500",
});

const spaceGrotesk = Space_Grotesk({ 
  subsets: ["latin"],
  weight: "500",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "CodeLab Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}  ${inter.className} ${spaceGrotesk.className}`}>
        {children}
      </body>
    </html>
  );
}
